-- upgrade --
CREATE TABLE IF NOT EXISTS "map" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "map_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "username_id" VARCHAR(50) NOT NULL REFERENCES "user" ("username") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "table" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "username_id" VARCHAR(50) NOT NULL REFERENCES "user" ("username") ON DELETE CASCADE
);-- downgrade --
DROP TABLE IF EXISTS "map";
DROP TABLE IF EXISTS "table";
