site_name: QwikGeo API Docs
site_url: https://docs.qwikgeo.com/
site_description: Tech docs for QwikGeo
site_author: Michael Keller

repo_url: https://github.com/qwikgeo/qwikgeo-api
repo_name: QwikGeo API
edit_uri: blob/main/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/images/favicon.ico

markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

dev_addr: '127.0.0.1:5000'

extra:
  analytics:
    provider: google
    property: G-2LXJZ67GEV